
server:
  port: 9021
spring:
  application:
    name: elastic-service
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7900/eureka/

elastic:
  host: 192.168.31.150
  port: 9200
  scheme : http
  index : note