spring:
  cloud:
    config:
      uri: http://127.0.0.1:30201
      profile: dev
      label: master
  zipkin:
    enabled: false
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:30200/eureka/
  instance:
    prefer-ip-address: true