spring:
  cloud:
    config:
      uri: http://192.168.31.154:30201
      profile: docker
      label: master
eureka:
  client:
    service-url:
      defaultZone: http://192.168.31.154:30200/eureka/
  instance:
    prefer-ip-address: true