spring:
  cloud:
    config:
      uri: http://192.168.31.154:30201
      profile: docker
      label: master
  zipkin:
    base-url: http://192.168.31.158:30411
eureka:
  client:
    service-url:
      defaultZone: http://192.168.31.154:30200/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
