server:
  port: 30600
  servlet:
    encoding:
      charset: utf-8
      force-response: true
spring:
  application:
    name: SERVICE-DOC
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always