

server:
  port: 9051
spring:
  application:
    name: mail-service
  redis:
    host: 192.168.31.150
    port: 6379
    password: 123456789
    timeout : 5000
    database: 15

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7900/eureka/