spring:
  redis:
    host: 192.168.31.150
    port: 6379
    password: 123456789
    database: 0
    jedis:
      pool:
        max-idle: 200
        min-idle: 0
        max-active: 50
        max-wait: 10000
  cloud:
    config:
      uri: http://127.0.0.1:30201
      profile: dev
      #      discovery:
      #        enabled: true
      #        service-id: config-service
      label: master

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:30200/eureka/
  instance:
    prefer-ip-address: true