server:
  port: 30500
  servlet:
    encoding:
      charset: utf-8
      force-response: true
spring:
  application:
    name: API-BLOG
  config:
    import: "optional:configserver:"
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always