spring:
  cloud:
    config:
      uri: http://192.168.31.154:30201
      profile: docker
      #      discovery:
      #        enabled: true
      #        service-id: config-service
      label: master
  zipkin:
    base-url: http://192.168.31.158:30411
eureka:
  client:
    service-url:
      defaultZone: http://192.168.31.154:30200/eureka/
  instance:
    prefer-ip-address: true