server:
  port: 30500
  servlet:
    encoding:
      charset: utf-8
      force-response: true
spring:
  application:
    name: API-BLOG
  config:
    import: "optional:configserver:"
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
      ACCEPT_SINGLE_VALUE_AS_ARRAY: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always