spring:
  datasource:
    username: fzcode
    password: 123456
    url: jdbc:mysql://192.168.31.150:3306/fzcode?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2b8
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: com.fzcode.servicenote.config.Mysql
  cloud:
    config:
      uri: http://127.0.0.1:30201
      profile: dev
      #      discovery:
      #        enabled: true
      #        service-id: config-service
      label: master
  zipkin:
    enabled: false
  elasticsearch:
    rest:
      uris: http://192.168.31.153:30200
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:30200/eureka/
  instance:
    prefer-ip-address: true