
server:
  port: 8888
spring:
  application:
    name: config-service
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:config/services/auth
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7900/eureka/