
server:
  port: 8888
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: git@github.com:757566833/fzcode-config-center.git
#    config:
#      server:
#        native:
#          search-locations: classpath:config/services/auth
#eureka:
#  client:
#    service-url:
#      defaultZone: http://127.0.0.1:7900/eureka/