spring:
  profiles:
    include: common
  redis:
    host: 192.168.31.150
    port: 9379
    password: 123456789
    database: 15

eureka:
  client:
    service-url:
      defaultZone: http://192.168.31.154:30200/eureka/