server:
  port: 30650
  servlet:
    encoding:
      charset: utf-8
      force-response: true
spring:
  application:
    name: CLOUD-ADMIN
  security:
    user:
      name: root
      password: root
