spring:
  cloud:
    config:
      uri: http://192.168.31.154:30201
      profile: docker
      #      discovery:
      #        enabled: true
      #        service-id: config-service
      label: master
  mail:
    host: smtp.126.com
    username: fzcode@126.com
    password: TKOMBJXTWWYJQTMS
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  boot:
    admin:
      notify:
        mail:
          from: fzcode@126.com
          to: 757566833@qq.com
      monitor:
        default-timeout: 60000
        status-interval: 15000
        status-lifetime: 15000
eureka:
  client:
    service-url:
      defaultZone: http://192.168.31.154:30200/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

