
spring:
  profiles:
    include: common
  boot:
    admin:
      client:
        url: http://192.168.31.155:30650
eureka:
  client:
    service-url:
      defaultZone: http://192.168.31.154:30200/eureka/
  instance:
    prefer-ip-address: true
