spring:
  profiles:
    include: common
  boot:
    admin:
      client:
        url: http://127.0.0.1:30650
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:30200/eureka/
  instance:
    prefer-ip-address: true